pipeline {
    agent any
    stages {
        stage('Test') {
            steps {
                sh 'npm install'
                sh 'npm run test'
            }
        }
      
        stage('Build') { 
            steps {
                sh 'npm install' 
                sh 'npm run build' 
            }
        }

        stage('Deploy') {
            steps {
                print 'Dummy deployment stage'
            }
        }
    }
}
